from __future__ import annotations

import path as path
import fs as fs

# @origin scripts/import_tokens_to_sub2api.js:26
def convertOne(tokenFile: Any) -> Any:
    Date.now(...)
    Math.random(...)
    toString(...)
    slice(...)
    execFileSync(...)
    JSON.parse(...)
    fs.readFileSync(...)
    return fs.unlinkSync(...)

# @origin scripts/import_tokens_to_sub2api.js:36
async def main() -> Any:
    await fetch(...)
    process.argv.slice(...)
    console.error(...)
    process.exit(...)
    Number(...)
    fs.statSync(...)
    isDirectory(...)
    fs.existsSync(...)
    fs.readdirSync(...)
    filter(...)
    test(...)
    sort(...)
    map(...)
    path.join(...)
    console.log(...)
    Set(...)
    convertOne(...)
    path.basename(...)
    seenFingerprints.has(...)
    seenFingerprints.add(...)
    accounts.push(...)
    Date(...)
    toISOString(...)
    fs.readFileSync(...)
    txt.match_(...)
    execFileSync(...)
    logs.match_(...)
    RegExp(...)
    trim(...)
    pick(...)
    readPgCredsFromEnv(...)
    ensurePgcrypto(...)
    out.trim(...)
    fs.writeFileSync(...)
    orig.replace(...)
    console.warn(...)
    readEnvAdminPass(...)
    readContainerLogPass(...)
    JSON.stringify(...)
    then(...)
    r.json(...)
    resetAdminPassViaPg(...)
    of(...)
    return items.filter(...)
