# session_state.py  (auto-generated by context compressor)
# ════════════════════════════════════════════════════════════════
# COMPRESSED SESSION STATE
# This file captures decisions, constraints, and task progress
# from the conversation. Re-inject into Context on each turn.
# Turn: 3
# Total turns: 3
# Raw chars ingested: 211
# Compressed chars: 904
# ════════════════════════════════════════════════════════════════
from __future__ import annotations
from typing import Dict, List, Optional


class CurrentSession:
    primary_goal = 'Not yet defined'
    last_updated_turn = 3

    class Decisions:
        ...  # No decisions recorded yet

    class Constraints:
        ...  # No constraints recorded yet

    class Tasks:
        ...  # No tasks recorded yet

def get_context() -> CurrentSession:
    """Return the current session state for injection into Context."""
    return CurrentSession
