# session_metrics.py  (auto-generated by context compressor)
# Diagnostic snapshot for context compression quality and coverage.
from __future__ import annotations

class SessionMetrics:
    session_id = '870c1cbd-e868-4e61-a9b8-b67a10c7648f'
    total_turns = 3
    last_updated_turn = 3
    raw_chars_ingested = 211
    compressed_chars = 904
    compression_ratio = 0.23
    decisions_total = 0
    decisions_accepted = 0
    decisions_rejected = 0
    decisions_proposed = 0
    constraints_active = 0
    tasks_total = 0
    tasks_completed = 0
    tasks_blocked = 0
    facts_total = 0
    code_anchors_total = 0
    error_memories_total = 0

def get_metrics() -> SessionMetrics:
    return SessionMetrics
