from __future__ import annotations

# import ../src/hub_modules.sa

# @origin sa/tests/rpc_emit_contract_test.sa:354
def assert_contract(ok: u8, code: i32) -> Any:
    ...

# @origin sa/tests/rpc_emit_contract_test.sa:367
def assert_buffer_contains(buf: ptr, len: u64, needle: ptr, needle_len: u64, code: i32) -> Any:
    sa_bytes_find(...)
    assert_contract(...)
    json_writer_write_empty_array_field_result(...)
    json_writer_finish_view(...)
    assert_buffer_contains(...)
    json_writer_dispose_finished(...)
    json_writer_write_empty_data_page_result(...)
    json_writer_write_plugin_install_unavailable_result(...)
    json_writer_write_config_requirements_result(...)
    json_writer_write_plugin_marketplaces_result(...)
    json_writer_write_experimental_features_result(...)
    json_writer_write_account_login_state_result(...)
    json_writer_write_approval_accept_result(...)
    json_writer_write_mcp_elicit_accept_result(...)
    json_writer_write_permissions_default_result(...)
    json_writer_write_user_input_continue_result(...)
    json_writer_write_command_exec_result(...)
    json_writer_write_process_spawn_result(...)
    json_writer_write_bool_field_result(...)
    json_writer_write_model_capabilities_result(...)
    json_writer_write_collaboration_mode_list_result(...)
    json_writer_write_hooks_list_result(...)
    json_writer_write_account_read_result(...)
    json_writer_write_rate_limits_result(...)
    json_writer_write_remote_status_params(...)
    state_init(...)
    state_notify_cursor(...)
    notify_remote_status(...)
    state_notify_read(...)
    json_writer_write_external_import_result(...)
    json_writer_write_chatgpt_tokens_refresh_result(...)
    json_writer_write_plugin_share_save_result(...)
    json_writer_write_plugin_share_checkout_result(...)
    json_writer_write_plugin_share_delete_result(...)
    json_writer_write_plugin_share_update_empty_result(...)
    sa_json_parse(...)
    json_writer_write_plugin_share_update_node_result(...)
    sa_json_free(...)
    json_writer_write_plugin_read_result(...)
    json_writer_write_plugin_uninstall_result(...)
    json_writer_write_marketplace_add_result(...)
    json_writer_write_marketplace_remove_result(...)
    json_writer_write_marketplace_upgrade_result(...)
    json_writer_write_send_credits_result(...)
    json_writer_write_initialize_result(...)
    json_writer_write_account_login_start_result(...)
    json_writer_write_environment_add_result(...)
    json_writer_write_review_start_result(...)
    json_writer_write_oauth_login_result(...)
    json_writer_write_mock_experimental_result(...)
    json_writer_write_external_detect_result(...)
    json_writer_write_sandbox_setup_result(...)
    json_writer_write_fuzzy_search_result(...)
    json_writer_write_fuzzy_session_result(...)
    return json_writer_write_server_resolved_result(...)
